baseurl = "https://cluster.ipfs.io"
languageCode = "en-us"
relativeURLs = true
sourceRelativeLinksEval = true
ignoreFiles = [ "\\.less$" ]
sectionPagesMenu = "main"
googleAnalytics = "UA-96910779-7"

theme = "hugo-theme-learn"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[params]
  name = "IPFS Cluster"
  title = "IPFS Cluster"
  description = "Pinset orchestration for IPFS"
  author = "Protocol Labs"
  github = "https://github.com/ipfs/ipfs-cluster"
  domain = "cluster.ipfs.io"
  og_image = "https://cluster.ipfs.io/og-image.jpg"
  download = "https://dist.ipfs.io/#ipfs-cluster-service"
  disableBreadcrumb = false
  disableNextPrev = true
  disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Releases"
url = "#"
weight = 1

# activate learn-theme's search
[outputs]
  home = [ "HTML", "RSS", "JSON"]
